export type Linea = 'alkorplan-2000' | 'alkorplan-3000' | 'ceramics' | 'touch-3d'

export interface Membrana {
  id: string
  nombre: string
  linea: Linea
  lineaNombre: string
  descripcion: string
  garantia: string
  grosor: string
  slug: string
  color: string // hex aproximado para la UI
  imagen: string // Unsplash placeholder
}

export const membranas: Membrana[] = [
  // ── ALKORPLAN 2000 ─────────────────────────────────────────────────────────
  {
    id: '2000-blanco',
    nombre: 'Blanco',
    linea: 'alkorplan-2000',
    lineaNombre: 'ALKORPLAN 2000',
    descripcion: 'Piscinas luminosas, cristalinas y frescas, siempre elegantes, para disfrutar del sol y del verano.',
    garantia: '10 años',
    grosor: '1.5mm',
    slug: 'blanco',
    color: '#F5F5F5',
    imagen: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800&q=80',
  },
  {
    id: '2000-arena',
    nombre: 'Arena',
    linea: 'alkorplan-2000',
    lineaNombre: 'ALKORPLAN 2000',
    descripcion: 'Luz en tu piscina de agua tibia y cristalina, como en lejanas y exóticas playas tropicales.',
    garantia: '10 años',
    grosor: '1.5mm',
    slug: 'arena',
    color: '#C2A66A',
    imagen: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80',
  },
  {
    id: '2000-azul-claro',
    nombre: 'Azul Claro',
    linea: 'alkorplan-2000',
    lineaNombre: 'ALKORPLAN 2000',
    descripcion: 'Piscinas eternas llenas de luz, color y alegría para pasar grandes momentos inolvidables.',
    garantia: '10 años',
    grosor: '1.5mm',
    slug: 'azul-claro',
    color: '#5BB8D4',
    imagen: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?w=800&q=80',
  },
  {
    id: '2000-azul-adriatico',
    nombre: 'Azul Adriático',
    linea: 'alkorplan-2000',
    lineaNombre: 'ALKORPLAN 2000',
    descripcion: 'El azul intenso del mar Mediterráneo en piscinas llenas de color y efervescencia.',
    garantia: '10 años',
    grosor: '1.5mm',
    slug: 'azul-adriatico',
    color: '#1B6CA8',
    imagen: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
  },
  {
    id: '2000-gris-claro',
    nombre: 'Gris Claro',
    linea: 'alkorplan-2000',
    lineaNombre: 'ALKORPLAN 2000',
    descripcion: 'Piscinas cosmopolitas, minimalistas y de gran belleza que nunca pasarán de moda.',
    garantia: '10 años',
    grosor: '1.5mm',
    slug: 'gris-claro',
    color: '#AAAAAA',
    imagen: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
  },
  {
    id: '2000-gris-oscuro',
    nombre: 'Gris Oscuro',
    linea: 'alkorplan-2000',
    lineaNombre: 'ALKORPLAN 2000',
    descripcion: 'Piscinas elegantes, sensuales y eternas que darán prestigio y belleza a tu jardín.',
    garantia: '10 años',
    grosor: '1.5mm',
    slug: 'gris-oscuro',
    color: '#555555',
    imagen: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
  },

  // ── ALKORPLAN 3000 ─────────────────────────────────────────────────────────
  {
    id: '3000-persia-azul',
    nombre: 'Persia Azul',
    linea: 'alkorplan-3000',
    lineaNombre: 'ALKORPLAN 3000',
    descripcion: 'Piscinas de carácter clásico que siempre triunfan y resultan, sin duda, una buena elección en todo momento.',
    garantia: '15 años',
    grosor: '1.5mm',
    slug: 'persia-azul',
    color: '#2A5FA5',
    imagen: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  },
  {
    id: '3000-persia-arena',
    nombre: 'Persia Arena',
    linea: 'alkorplan-3000',
    lineaNombre: 'ALKORPLAN 3000',
    descripcion: 'Piscinas de colores suaves y elegantes que desprenden luz y armonía, haciendo del baño una experiencia única.',
    garantia: '15 años',
    grosor: '1.5mm',
    slug: 'persia-arena',
    color: '#D4AA70',
    imagen: 'https://images.unsplash.com/photo-1439539698758-ba2680ecabd9?w=800&q=80',
  },
  {
    id: '3000-persia-negro',
    nombre: 'Persia Negro',
    linea: 'alkorplan-3000',
    lineaNombre: 'ALKORPLAN 3000',
    descripcion: 'Piscinas de lujo, sobrias, serenas y elegantes, que serán el toque de distinción en tu jardín.',
    garantia: '15 años',
    grosor: '1.5mm',
    slug: 'persia-negro',
    color: '#1A1A1A',
    imagen: 'https://images.unsplash.com/photo-1562778612-e1e0cda9915c?w=800&q=80',
  },
  {
    id: '3000-mosaico',
    nombre: 'Mosaico',
    linea: 'alkorplan-3000',
    lineaNombre: 'ALKORPLAN 3000',
    descripcion: 'Piscinas de gran belleza y destellos claros, que evocan el lujo de los antiguos tiempos imperiales.',
    garantia: '15 años',
    grosor: '1.5mm',
    slug: 'mosaico',
    color: '#3B82A0',
    imagen: 'https://images.unsplash.com/photo-1572097662960-c0d6cfbfd74d?w=800&q=80',
  },
  {
    id: '3000-carrara',
    nombre: 'Carrara',
    linea: 'alkorplan-3000',
    lineaNombre: 'ALKORPLAN 3000',
    descripcion: 'Piscinas alegres, de tonalidad azulada con un estampado elegante, ideal para vasos de forma irregular.',
    garantia: '15 años',
    grosor: '1.5mm',
    slug: 'carrara',
    color: '#E8ECF0',
    imagen: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
  },
  {
    id: '3000-marbra',
    nombre: 'Marbra',
    linea: 'alkorplan-3000',
    lineaNombre: 'ALKORPLAN 3000',
    descripcion: 'Piscinas de un azul intenso y reflejos espectaculares que serán el centro de todas las miradas.',
    garantia: '15 años',
    grosor: '1.5mm',
    slug: 'marbra',
    color: '#1E6B8C',
    imagen: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
  },
  {
    id: '3000-bizancio-azul',
    nombre: 'Bizancio Azul',
    linea: 'alkorplan-3000',
    lineaNombre: 'ALKORPLAN 3000',
    descripcion: 'Piscinas elegantes y distinguidas, que transmiten bienestar y no pasan nunca de moda.',
    garantia: '15 años',
    grosor: '1.5mm',
    slug: 'bizancio-azul',
    color: '#204080',
    imagen: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&q=80',
  },
  {
    id: '3000-platinum',
    nombre: 'Platinum',
    linea: 'alkorplan-3000',
    lineaNombre: 'ALKORPLAN 3000',
    descripcion: 'Piscinas de diseño, modernas y espectaculares, de reflejos brillantes — la joya más preciada de tu jardín.',
    garantia: '15 años',
    grosor: '1.5mm',
    slug: 'platinum',
    color: '#B8C0CC',
    imagen: 'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=800&q=80',
  },

  // ── CERAMICS ───────────────────────────────────────────────────────────────
  {
    id: 'ceramics-selene',
    nombre: 'Selene',
    linea: 'ceramics',
    lineaNombre: 'ALKORPLAN CERAMICS',
    descripcion: 'De blanco lunar, cautivará a quien contemple sus aguas celestes como el color del cielo en un día de verano.',
    garantia: '10 años',
    grosor: '2mm',
    slug: 'selene',
    color: '#E8F4F8',
    imagen: 'https://images.unsplash.com/photo-1560749003-f4b1e17e2dfd?w=800&q=80',
  },
  {
    id: 'ceramics-etna',
    nombre: 'Etna',
    linea: 'ceramics',
    lineaNombre: 'ALKORPLAN CERAMICS',
    descripcion: 'De matices sobrios y elegantes, Etna consigue que las piscinas sean espectaculares y regias.',
    garantia: '10 años',
    grosor: '2mm',
    slug: 'etna',
    color: '#6B7280',
    imagen: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80',
  },
  {
    id: 'ceramics-sofia',
    nombre: 'Sofia',
    linea: 'ceramics',
    lineaNombre: 'ALKORPLAN CERAMICS',
    descripcion: 'De un color totalmente novedoso en el mundo de las piscinas, ofrece un espectáculo de color turquesa delicado y sutil.',
    garantia: '10 años',
    grosor: '2mm',
    slug: 'sofia',
    color: '#00BCD4',
    imagen: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
  },
  {
    id: 'ceramics-atenea',
    nombre: 'Atenea',
    linea: 'ceramics',
    lineaNombre: 'ALKORPLAN CERAMICS',
    descripcion: 'De un azul intenso, tan cálido, tan profundo y tan nuestro. Atenea otorga al agua un brillo y un matiz inigualable.',
    garantia: '10 años',
    grosor: '2mm',
    slug: 'atenea',
    color: '#1565C0',
    imagen: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80',
  },

  // ── TOUCH 3D ───────────────────────────────────────────────────────────────
  {
    id: 'touch-authentic',
    nombre: 'Authentic',
    linea: 'touch-3d',
    lineaNombre: 'ALKORPLAN TOUCH 3D',
    descripcion: 'Piscinas agrestes, con textura de piedra y tacto cautivador, ideales para entornos naturales o jardines rústicos.',
    garantia: '15 años',
    grosor: '2mm',
    slug: 'authentic',
    color: '#8B7355',
    imagen: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
  },
  {
    id: 'touch-relax',
    nombre: 'Relax',
    linea: 'touch-3d',
    lineaNombre: 'ALKORPLAN TOUCH 3D',
    descripcion: 'Piscinas exóticas de reflejos turquesa que te transportan a playas lejanas del Mar Caribe.',
    garantia: '15 años',
    grosor: '2mm',
    slug: 'relax',
    color: '#00ACC1',
    imagen: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
  },
  {
    id: 'touch-elegance',
    nombre: 'Elegance',
    linea: 'touch-3d',
    lineaNombre: 'ALKORPLAN TOUCH 3D',
    descripcion: 'Piscinas seductoras y únicas, de un azul profundo, que te cautivarán desde el primer momento.',
    garantia: '15 años',
    grosor: '2mm',
    slug: 'elegance',
    color: '#1A3A6B',
    imagen: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=800&q=80',
  },
  {
    id: 'touch-vanity',
    nombre: 'Vanity',
    linea: 'touch-3d',
    lineaNombre: 'ALKORPLAN TOUCH 3D',
    descripcion: 'Piscinas ostentosas y espectaculares de mármol blanco que estimulan la vanidad de sus propietarios.',
    garantia: '15 años',
    grosor: '2mm',
    slug: 'vanity',
    color: '#F0ECE8',
    imagen: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80',
  },
  {
    id: 'touch-sublime',
    nombre: 'Sublime',
    linea: 'touch-3d',
    lineaNombre: 'ALKORPLAN TOUCH 3D',
    descripcion: 'Piscinas nobles de mármol travertino y cálidos reflejos, idóneas para entornos exclusivos y naturales.',
    garantia: '15 años',
    grosor: '2mm',
    slug: 'sublime',
    color: '#C4A882',
    imagen: 'https://images.unsplash.com/photo-1622552867218-d55b8979dc4e?w=800&q=80',
  },
  {
    id: 'touch-prestige',
    nombre: 'Prestige',
    linea: 'touch-3d',
    lineaNombre: 'ALKORPLAN TOUCH 3D',
    descripcion: 'Piscinas que evocan un paraíso de roca volcánica, especialmente pensadas para entornos minimalistas y de diseño.',
    garantia: '15 años',
    grosor: '2mm',
    slug: 'prestige',
    color: '#2D2D2D',
    imagen: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
  },
]

export const lineas = [
  { id: 'alkorplan-2000', nombre: 'ALKORPLAN 2000', descripcion: 'Unicolor, 1.5mm, garantía 10 años' },
  { id: 'alkorplan-3000', nombre: 'ALKORPLAN 3000', descripcion: 'Estampada, 1.5mm, garantía 15 años' },
  { id: 'ceramics', nombre: 'ALKORPLAN CERAMICS', descripcion: 'Con relieve, 2mm, certificado antideslizante' },
  { id: 'touch-3d', nombre: 'ALKORPLAN TOUCH 3D', descripcion: 'Texturizada 3D, 2mm, garantía 15 años' },
] as const
