export type TipoProyecto = 'construccion' | 'renovacion' | 'equipamiento' | 'torre' | 'hotel'

export interface Proyecto {
  id: string
  titulo: string
  año: number
  ubicacion: string
  estado: string
  tipo: TipoProyecto
  membrana: string
  descripcion: string
  caracteristicas: string[]
  imagen: string
  imagenes: string[]
  destacado: boolean
}

export const proyectos: Proyecto[] = [
  {
    id: 'vistas-angel-2016',
    titulo: 'Vistas del Ángel',
    año: 2016,
    ubicacion: 'Riviera de Chapala, Jocotepec',
    estado: 'Jalisco',
    tipo: 'renovacion',
    membrana: 'RENOLIT ALKORPLAN 2000 Blanco',
    descripcion: 'Renovación de alberca rectangular con fugas mediante membrana blanca de alto brillo. Recuperación total de estanqueidad sin demolición.',
    caracteristicas: ['3.5m × 7m × 1.4m', 'Renovación sin demolición', 'ALKORPLAN 2000 Blanco'],
    imagen: 'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=1200&q=85',
      'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'las-canadas-2016',
    titulo: 'Las Cañadas',
    año: 2016,
    ubicacion: 'Zapopan',
    estado: 'Jalisco',
    tipo: 'renovacion',
    membrana: 'RENOLIT ALKORPLAN 2000 Azul Claro + 3000',
    descripcion: 'Restauración con sistema RENOLIT doble línea. Instalación de cascada LED para iluminación nocturna espectacular.',
    caracteristicas: ['Cascada LED', 'Combinación 2000 + 3000', 'Iluminación subacuática'],
    imagen: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'zapopan-resort-2017',
    titulo: 'Zapopan Resort',
    año: 2017,
    ubicacion: 'Zapopan',
    estado: 'Jalisco',
    tipo: 'renovacion',
    membrana: 'RENOLIT ALKORPLAN 2000 + 3000 (Mosaico Azul, Azul Adriático)',
    descripcion: 'Renovación premium con diseño de membranas combinadas. Muros en mosaico azul, bancas y huellas en Azul Adriático. Andador en Kuarzo resina.',
    caracteristicas: ['Diseño combinado 2000 + 3000', 'Andador Kuarzo resina', 'Bancas y huellas integradas'],
    imagen: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'pinar-venta-astillero-2017',
    titulo: 'Pinar de la Venta del Astillero',
    año: 2017,
    ubicacion: 'Jalisco',
    estado: 'Jalisco',
    tipo: 'renovacion',
    membrana: 'RENOLIT ALKORPLAN 2000 Lisa Color Arena',
    descripcion: 'Renovación de alberca y jacuzzi con fugas críticas. Sistema ALKORPLAN Arena para integración con el entorno natural del bosque.',
    caracteristicas: ['Alberca + jacuzzi', 'Acabado Arena', 'Zona boscosa'],
    imagen: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'torre-latitud-2019',
    titulo: 'Torre Latitud Providencia',
    año: 2019,
    ubicacion: 'Guadalajara',
    estado: 'Jalisco',
    tipo: 'torre',
    membrana: 'RENOLIT ALKORPLAN 2000 Azul Adriático',
    descripcion: 'Alberca de gran formato en torre residencial de lujo en Providencia. Sistema constructivo tradicional con muros de block, dalas y losa de concreto armado.',
    caracteristicas: ['20m × 10m × 1.4m', 'Torre residencial', 'Filtrado básico profesional', 'Ramales hidráulicos'],
    imagen: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200&q=85',
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=85',
    ],
    destacado: true,
  },
  {
    id: 'hotel-don-jose-2019',
    titulo: 'Hotel Don José',
    año: 2019,
    ubicacion: 'Lo de Marcos',
    estado: 'Nayarit',
    tipo: 'hotel',
    membrana: 'RENOLIT ALKORPLAN 2000 Gris Claro',
    descripcion: 'Renovación de alberca hotelera con sistema RENOLIT premium. Filtrado alemán, iluminación LED subacuática y equipos Astral Pool de alto rendimiento.',
    caracteristicas: ['Filtrado alemán', 'Iluminación LED Jandy', 'Equipos Astral Pool', 'Gris Claro cosmopolita'],
    imagen: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=85',
    ],
    destacado: true,
  },
  {
    id: 'san-esteban-2019',
    titulo: 'San Esteban',
    año: 2019,
    ubicacion: 'Zapopan',
    estado: 'Jalisco',
    tipo: 'renovacion',
    membrana: 'RENOLIT ALKORPLAN 2000 Azul Claro',
    descripcion: 'Renovación que duplicó el tamaño de la alberca original. De 3m a 6m de ancho con equipamiento completo de alta gama.',
    caracteristicas: ['3m → 6m ancho × 10m × 1.4m', 'Calefacción híbrida solar + bomba calor', 'Filtrado zeolita', 'Sanitización por dosificación'],
    imagen: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'torre-estrato-2019',
    titulo: 'Torre Estrato — Piso 22',
    año: 2019,
    ubicacion: 'Guadalajara',
    estado: 'Jalisco',
    tipo: 'torre',
    membrana: 'RENOLIT ALKORPLAN TOUCH 3D Relax + Elegance',
    descripcion: 'Proyecto emblemático: carril de nado en el piso 22 de la Torre Estrato con jacuzzi integrado. Membrana TOUCH 3D de 2mm para condiciones de altura extrema.',
    caracteristicas: ['Carril nado: 2.36m × 23.60m', 'Jacuzzi integrado', 'Piso 22', 'TOUCH 3D Relax + Elegance'],
    imagen: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=85',
      'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=1200&q=85',
    ],
    destacado: true,
  },
  {
    id: 'villa-corona-2019',
    titulo: 'Villa Corona',
    año: 2019,
    ubicacion: 'Villa Corona',
    estado: 'Jalisco',
    tipo: 'renovacion',
    membrana: 'RENOLIT ALKORPLAN 2000 Azul Claro',
    descripcion: 'Renovación de rancho particular con equipamiento completo de alta gama: nado contra corriente, chorros LED laminares, calefacción, automatización y cascada laminar.',
    caracteristicas: ['6m × 12m × 1.4m + chapoteadero', 'Nado contra corriente', 'Chorros borbotón LED', 'Calefacción + automatización', 'Cascada laminar'],
    imagen: 'https://images.unsplash.com/photo-1572097662960-c0d6cfbfd74d?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1572097662960-c0d6cfbfd74d?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'casa-fuerte-2019',
    titulo: 'Casa Fuerte',
    año: 2019,
    ubicacion: 'Tlajomulco de Zúñiga',
    estado: 'Jalisco',
    tipo: 'renovacion',
    membrana: 'RENOLIT ALKORPLAN 2000 Azul Adriático',
    descripcion: 'Restauración de casa club por fugas recurrentes. Sistema RENOLIT con garantía de estanqueidad de 10 años sobre alberca de gran formato.',
    caracteristicas: ['7m × 15m × 1.3m', 'Casa club', 'Restauración por fugas'],
    imagen: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'casa-cangrejo-2019',
    titulo: 'Casa Cangrejo',
    año: 2019,
    ubicacion: 'Vida del Mar, El Naranjo',
    estado: 'Colima (Manzanillo)',
    tipo: 'construccion',
    membrana: 'RENOLIT ALKORPLAN TOUCH 3D Vanity + Extreme Onix',
    descripcion: 'Alberca infinita frente al mar con doble membrana TOUCH 3D. Iluminación Jandy Hidro Cool con 4 reflectores subacuáticos para espectáculo nocturno.',
    caracteristicas: ['14m × 4m + escaleras 4m × 2.5m', 'Alberca infinita', '4 reflectores Jandy Hidro Cool 6w 12v', 'TOUCH 3D Vanity + Extreme Onix'],
    imagen: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=85',
    ],
    destacado: true,
  },
  {
    id: 'sayulita-2019',
    titulo: 'Sayulita',
    año: 2019,
    ubicacion: 'Sayulita',
    estado: 'Nayarit',
    tipo: 'construccion',
    membrana: 'RENOLIT ALKORPLAN TOUCH Vanity / 2000 + 3000',
    descripcion: 'Proyecto de playa con equipamiento completo de automatización. Jets, chorros LED laminares, nado contra corriente y bombeo WiFi integrado.',
    caracteristicas: ['5m × 10m × 1.3m', 'Jets y chorros LED', 'Nado contra corriente', 'Bombeo WiFi', 'Automatización completa'],
    imagen: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'la-cruz-encantada-2020',
    titulo: 'La Cruz Encantada',
    año: 2020,
    ubicacion: 'La Cruz de Huanacaxtle',
    estado: 'Nayarit',
    tipo: 'construccion',
    membrana: 'RENOLIT ALKORPLAN 2000 Azul Claro',
    descripcion: 'Alberca en 4to piso con recubrimiento general y equipamiento completo. Proyecto de costa pacífica con sistema de impermeabilización de alto rendimiento.',
    caracteristicas: ['Alberca en piso 4', 'Equipamiento completo', 'Costa Pacífica'],
    imagen: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'torre-andares-2021',
    titulo: 'Torre Andares',
    año: 2021,
    ubicacion: 'Guadalajara',
    estado: 'Jalisco',
    tipo: 'torre',
    membrana: 'RENOLIT ALKORPLAN 2000 Blanco Liso',
    descripcion: 'Reparación, equipamiento y revestimiento final en una de las torres más icónicas de Guadalajara. Estética minimalista y blanca.',
    caracteristicas: ['Torre emblemática GDL', 'Reparación + equipamiento', 'ALKORPLAN 2000 Blanco'],
    imagen: 'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=1200&q=85',
    ],
    destacado: false,
  },
  {
    id: 'valle-de-bravo-2021',
    titulo: 'Valle de Bravo',
    año: 2021,
    ubicacion: 'Valle de Bravo',
    estado: 'Estado de México',
    tipo: 'construccion',
    membrana: 'RENOLIT ALKORPLAN TOUCH 3D Elegance',
    descripcion: 'Proyecto premium de alta gama con automatización total. El sistema más completo construido: jets, chorros borbotón LED, nado contra corriente, cascada laminar, bomba de calor eléctrica, intercambiador solar y cubierta enrolable.',
    caracteristicas: ['5m × 10m × 1.3m', 'Jets y chorros borbotón LED', 'Nado contra corriente', 'Cascada LED laminar', 'Bombeo WiFi', 'Bomba calor eléctrico', 'Intercambiador solar', 'Automatización completa', 'Cubierta enrolable'],
    imagen: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=85',
      'https://images.unsplash.com/photo-1560749003-f4b1e17e2dfd?w=1200&q=85',
    ],
    destacado: true,
  },
  {
    id: 'plaza-midtown-2022',
    titulo: 'Plaza Midtown',
    año: 2022,
    ubicacion: 'Guadalajara',
    estado: 'Jalisco',
    tipo: 'construccion',
    membrana: 'RENOLIT ALKORPLAN 2000 (varios colores)',
    descripcion: 'Diseño termofusionado de membrana en espejos de agua de plaza comercial de lujo. Acabado decorativo de alto impacto visual para espacio público premium.',
    caracteristicas: ['Espejos de agua comercial', 'Diseño termofusionado', 'Multicolor', 'Espacio público premium'],
    imagen: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&q=85',
    imagenes: [
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200&q=85',
    ],
    destacado: false,
  },
]

export const tipoLabels: Record<TipoProyecto, string> = {
  construccion: 'Construcción',
  renovacion: 'Renovación',
  equipamiento: 'Equipamiento',
  torre: 'Torre / Edificio',
  hotel: 'Hotel / Comercial',
}
